# Generated by Django 4.2.25 on 2025-10-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_relationships_user_following'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Relationships',
            new_name='Relationship',
        ),
    ]
